pipelines:
  default:
    - step:
        name: Build project
        services:
          - jdk
        caches:
          - gradle
          - gradlewrapper
        script:
          - bash ./gradlew build
        artifacts:
          - examples/ref-app/reference-jira-app-performance-tests/target/**
  branches:
    master:
      - step:
          name: Build project
          services:
            - jdk
          caches:
            - gradle
            - gradlewrapper
          script:
            - bash ./gradlew build
          artifacts:
            - examples/ref-app/reference-jira-app-performance-tests/target/**
      - step:
          name: Release project
          services:
            - jdk
          caches:
            - gradle
            - gradlewrapper
          trigger: manual
          script:
            - git config --global user.email "bitbucketci-team@atlassian.com"
            - git config --global user.name "Bitbucket Pipelines"
            - bash ./gradlew release -Prelease.customKeyFile="/opt/atlassian/pipelines/agent/data/id_rsa"
            - bash ./gradlew publish
  custom:
    aws-housekeeping:
      - step:
          name: AWS housekeeping
          services:
            - jdk
          script:
            - cd ./examples/ref-app
            - bash ./mvnw -f reference-jira-app-performance-tests/pom.xml test -DskipTests exec:java@clean-all-expired
definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper
  services:
    jdk:
      image: openjdk:8
      memory: 2048
